### ISSUE TITLE
你好麻烦请问厂商通道已经开通但是应用退出收不到信息是什么情况？

### ISSUE THREAD

**Issue by crapthings** [hhjjj1010/cordova-plugin-mobpush#5]
mobpush的厂商信息已经都填上了

https://github.com/hhjjj1010/cordova-plugin-mobpush/blob/master/src/android/mobpush.gradle

这里对应的 key id secret 也都填上了

这里有一个问题，这里边key 的配置有的有 appId 有的没有，有的没有appSecret，是漏写了还是 sdk 里就这么要求的？

```
apply plugin: 'com.mob.sdk'

// 在MobSDK的扩展中注册MobPush的相关信息
MobSDK {
appKey "替换为mob官方申请的appkey"
appSecret "替换为mob官方申请的appkey对应的appSecret"

MobPush {

    //设置角标开关（不需要可不设置）
    badge true
    //集成其他推送通道（可选）
    devInfo {
        //华为推送配置信息
        HUAWEI {
            appId "华为的appid"
        }

        //魅族推送配置信息
        MEIZU {
            appId "魅族的appid"
            appKey "魅族的appkey"
        }

        //小米推送配置信息
        XIAOMI {
            appId "小米的appid"
            appKey "小米的appkey"
        }
        //FCM推送通道配置
        FCM {
            //设置默认推送通知显示图标
            iconRes "@mipmap/ic_launcher"
        }

       //OPPO推送配置信息
        OPPO {
            appKey "OPPO的appKey"
            appSecret "OPPO的appSecret"
        }

        //VIVO推送配置信息
        VIVO {
           appId "应用对应的vivo appID"
           appKey "应用对应的vivo appKey"
        }

    }
}
```

**Comment by lovenan** [comment]
你的配的是哪个厂商的通道  你可以去找mobpush的官方客服看看

**Comment by crapthings** [comment]
看了一下官方文档，这个文件貌似官方也是这么要求的

**Comment by lovenan** [comment]
我配的小米通道是可以的

**Comment by lovenan** [comment]
我配置的小米的通道 是可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhjjj1010/cordova-plugin-mobpush"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午10:58
收件人:&nbsp;"hhjjj1010/cordova-plugin-mobpush"<cordova-plugin-mobpush@noreply.github.com&gt;;
抄送:&nbsp;"xu nan"<939503307@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hhjjj1010/cordova-plugin-mobpush] 你好麻烦请问厂商通道已经开通但是应用退出收不到信息是什么情况？ (#5)





 
看了一下官方文档，这个文件貌似官方也是这么要求的

**Comment by crapthings** [comment]
我的也是，oppo 不好使，其他的等实名认证呢

**Comment by lovenan** [comment]
但是这个插件点击推送信息的时候 好像没有触发mobpush.openedNotificationMessage&nbsp; &nbsp;白激动半天




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hhjjj1010/cordova-plugin-mobpush"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 中午12:23
收件人:&nbsp;"hhjjj1010/cordova-plugin-mobpush"<cordova-plugin-mobpush@noreply.github.com&gt;;
抄送:&nbsp;"xu nan"<939503307@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [hhjjj1010/cordova-plugin-mobpush] 你好麻烦请问厂商通道已经开通但是应用退出收不到信息是什么情况？ (#5)





 
我的也是，oppo 不好使，其他的等实名认证呢
